# See https://wiki.hyprland.org/Configuring/Monitors/

monitorv2 {
    output = DP-1
    mode = highres
    position = auto
    scale = 1
    vrr = 3
    bitdepth = 10
    supports_wide_color = 1
    supports_hdr = 1
}
