" Basic settings
set number
set mouse=r
syntax on
set smartcase
set encoding=utf-8
set termguicolors

" Indents
set expandtab
set shiftwidth=2
set softtabstop=2
set tabstop=2

" Cursor shape
let &t_SI = "\e[5 q"
let &t_EI = "\e[2 q"

" Enable spellcheck, :s
map <leader>s :setlocal spell! spelllang=en_us<CR>

" Toggle autoindent
map <leader>i :setlocal autoindent<CR>
map <leader>I :setlocal noautoindent<CR>

" Editor tabs
map <leader>tn :tabnew
map <leader>t<leader> :tabnext
map <leader>tm :tabmove
map <leader>tc :tabclose<CR>
map <leader>to :tabonly<CR>

" Alias for replace all, S
nnoremap S :%s//gI<Left><Left><Left>

" vim-plug
call plug#begin('~/.vim/plugged')
  Plug 'rrethy/vim-hexokinase', { 'do': 'make hexokinase' }
  Plug 'preservim/nerdtree'
call plug#end()

" vim-hexokinase (color highlighting)
let g:Hexokinase_highlighters = [ 'backgroundfull' ]
let g:Hexokinase_optInPatterns = 'full_hex,rgb,rgba,hsl,hsla,colour_names'
