# Set your monitors up if you need a different mode than the default chosen.

# Example:
# monitor = DP-2, 3840x2160@144, auto-right, auto
#        name ^    mode ^      position ^     ^ scale 

# If you need to find the name, or mode, execute `hyprctl monitors all` in the terminal.
# monitor = , 5120x1440@240, 0x0, 1, bitdepth, 10, vrr, 3, cm, hdredid

monitorv2 {
    output = DP-3
    mode = highres
    position = auto
    scale = 1
    vrr = 3
    bitdepth = 10
    supports_wide_color = 1
    supports_hdr = 1
}
