# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    gaps_in = 5
    gaps_out = 10

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = true

    # If true, will not fall back to the next available window when moving focus in a direction where no window was found
    no_focus_fallback = true

    allow_tearing = true

    snap  {
        enabled = true
        border_overlap = true
    }

    layout = master
}

# https://wiki.hypr.land/Configuring/Dwindle-Layout/
dwindle {
    force_split = 2
    permanent_direction_override = true
    pseudotile = true
    preserve_split = true
    special_scale_factor = 0.95
    single_window_aspect_ratio = 16 9
}

# https://wiki.hyprland.org/Configuring/Master-Layout/
master {
    mfact = 0.5
    new_status = master
    new_on_top = true
    orientation = right
    special_scale_factor = 0.95
    slave_count_for_center_master = 0
}

group {
    auto_group = true
    insert_after_current = false

    groupbar {
        gradients = false
        height = 0
        render_titles = false
    }
}

# https://wiki.hyprland.org/Configuring/Variables/#misc
misc {
    allow_session_lock_restore = true
    disable_hyprland_logo = false # If true disables the random hyprland logo / anime girl background. :(
    disable_splash_rendering = true
    force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
    enable_swallow = false
    focus_on_activate = true
    key_press_enables_dpms = true
    mouse_move_enables_dpms = true
    on_focus_under_fullscreen = 1
    vrr = 3
}

# https://wiki.hyprland.org/Configuring/Variables/#binds
binds {
    allow_workspace_cycles = true
    hide_special_on_workspace_change = true
    movefocus_cycles_fullscreen = true
    workspace_back_and_forth = false
}

# https://wiki.hyprland.org/Configuring/Variables/#cursor
cursor {
    inactive_timeout = 10
}

# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    float_switch_override_focus = 0
    follow_mouse = 2
    numlock_by_default = false
}

xwayland {
    force_zero_scaling = true
}

ecosystem {
    no_donation_nag = true
}
