# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    gaps_in = 5
    gaps_out = 10

    layout = master
}

# https://wiki.hyprland.org/Configuring/Master-Layout/
master {
    inherit_fullscreen = true
    mfact = 0.6
    new_status = master
    new_on_top = true
    orientation = right
    special_scale_factor = 0.95
    slave_count_for_center_master = 0
}

# https://wiki.hyprland.org/Configuring/Variables/#binds
binds {
    allow_workspace_cycles = true
    hide_special_on_workspace_change = true
    movefocus_cycles_fullscreen = true
    workspace_back_and_forth = false
}

# https://wiki.hyprland.org/Configuring/Variables/#cursor
cursor {
    inactive_timeout = 10
}
