#!/usr/bin/sh

# General exports
export XDG_CURRENT_DESKTOP=Hyprland
export XDG_SESSION_DESKTOP=wayland
export XDG_SESSION_TYPE=wayland

# Load user environment variables
if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/hypr/environment" ]; then
    set -o allexport
    . "${XDG_CONFIG_HOME:-$HOME/.config}/hypr/environment"
    set +o allexport
fi

# Start Hyprland
exec systemd-cat -- /usr/bin/Hyprland
