#!/bin/sh

$HOME/.config/scripts/autostart.sh

bspc wm -O DP-3 HDMI-0 DP-1
bspc monitor DP-3 -d 1 2 3
bspc monitor HDMI-0 -d 4 5 6
bspc monitor DP-1 -d 7 8 9

bspc config border_width         2
bspc config window_gap          10

bspc config normal_border_color "#020d23"
bspc config focused_border_color "#b39d6a"
bspc config presel_feedback_color "#be9d6a"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer false

# Firefox Picture-in-Picture
bspc rule -a '*:*:Picture-in-Picture' state=floating

# Assign applications to desktops
bspc rule -a Mailspring desktop='^2'

